<a href="https://colab.research.google.com/github/devinemonk/ML/blob/main/Decision%20Tree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_validate
from sklearn import datasets


In [30]:
iris_data=datasets.load_iris()

In [31]:
features=iris_data.data
target=iris_data.target

In [33]:
feature_train,feature_test,target_train,target_test=train_test_split(features,target,test_size=0.2)
model=DecisionTreeClassifier(criterion='entropy')
predicted=cross_validate(model,features,target,cv=10)
print(np.mean(predicted['test_score']))


0.96


In [34]:
model=DecisionTreeClassifier()
predicted=cross_validate(model,features,target,cv=10)
print(np.mean(predicted['test_score']))

0.9533333333333334


In [35]:
from sklearn.model_selection import GridSearchCV

In [40]:
param_grid={'max_depth':np.arange(1,10)}
tree=GridSearchCV(DecisionTreeClassifier(),param_grid)
tree.fit(feature_train,target_train)
print("Best parameter with grid search",tree.best_params_)
grid_predictions=tree.predict(feature_test)
print(confusion_matrix(target_test,grid_predictions))
print(accuracy_score(target_test,grid_predictions))

Best parameter with grid search {'max_depth': 3}
[[ 9  0  0]
 [ 0 11  2]
 [ 0  0  8]]
0.9333333333333333
