<a href="https://colab.research.google.com/github/devinemonk/ML/blob/main/Random%20Forest%20Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [41]:
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_validate
from sklearn import datasets


In [42]:
iris_data=datasets.load_iris()

In [43]:
features=iris_data.data
target=iris_data.target

In [47]:
feature_train,feature_test,target_train,target_test=train_test_split(features,target,test_size=0.2)
model=RandomForestClassifier(n_estimators=1000,max_features='sqrt')
fitted_model=model.fit(feature_train,target_train)
prediction=fitted_model.predict(feature_test)
print(confusion_matrix(target_test,prediction))
print(accuracy_score(target_test,prediction))


[[10  0  0]
 [ 0 12  0]
 [ 0  0  8]]
1.0


In [48]:
model=RandomForestClassifier()
predicted=cross_validate(model,features,target,cv=10)
print(np.mean(predicted['test_score']))

0.9666666666666666
