<a href="https://colab.research.google.com/github/devinemonk/ML/blob/main/Support%20Vector%20Machine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import numpy as np
import pandas as pd
from sklearn import svm
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn import datasets


In [21]:
iris_data=datasets.load_iris()

In [26]:
features=iris_data.data
target=iris_data.target

In [27]:
feature_train,feature_test,target_train,target_test=train_test_split(features,target,test_size=0.3)
model=svm.SVC()
fitted_model=model.fit(feature_train,target_train)
predictions=fitted_model.predict(feature_test)

print(confusion_matrix(target_test,predictions))
print(accuracy_score(target_test,predictions))

[[17  0  0]
 [ 0 15  0]
 [ 0  1 12]]
0.9777777777777777
